import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Router from "next/router";

export default function Home() {
	return (
		<div className="bg-gray-100">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className="bg-primary-400 py-24">
				<div className="container">
					<div className="flex flex-col items-center space-y-6">
						<div className="flex flex-col items-center space-y-3">
							<div className="relative w-32 h-10">
								<Image
									alt=""
									src="/images/goplay.png"
									layout="fill"
									objectFit="contain"
								/>
							</div>
							<h1 className="text-secondary-900 font-secondary font-bold text-6xl text-center">
								Senior Frontend Engineer Test
							</h1>
						</div>
						<div className="text-secondary-900 text-2xl font-light">
							Ahmed Rayhan Primadedas
						</div>
					</div>
				</div>
			</header>

			<main className="h-full py-12">
				<div className="container space-y-12">
					<h1 className="font-secondary text-center text-4xl font-bold">
						Components
					</h1>
					<div className="grid grid-cols-3">
						<Link href="#" passHref>
							<div className="bg-white cursor-pointer px-8 py-16 rounded-md shadow-md text-center text-2xl">
								Color Picker
							</div>
						</Link>
					</div>
				</div>
			</main>
		</div>
	);
}
